[package]
name = "slippi-netplay"
version = "0.1.0"
edition = "2024"

[dependencies]
dolphin-integrations = { path = "../dolphin" }
slippi-shared-types = { path = "../shared-types" }
slippi-user = { path = "../user" }

tracing = { workspace = true }
